title: Portfólio - Hugo Branco
description: > # this means to ignore newlines until "baseurl:"
  Project portfolio for Artificial Intelligence, Data Science and Web Design projects I’ve worked on.
permalink: ':title/'
#baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hugo Branco # add your name
author-img: profile.jpg # add your photo
about-author: Estudante de Engenharia de Controle e Automação pela Universidade de Pernambuco.
#social-twitter: hugobranco # add your Twitter handle
#social-facebook: hugorbancowb # add your Facebook handle
social-github: hugobrancowb # add your Github handle
social-linkedin: hugo-branco-627801136 # add your Linkedin handle
social-email: hugobrancowb@gmail.com # add your Email address

# Disqus
discus-identifier: #mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]